# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"
gem 'pg'

group :development, :test do # <<<< :development, not devlopment
  gem 'sqlite3'
end